// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutosubmitController from "./autosubmit_controller";
application.register("autosubmit", AutosubmitController);

import DraggableController from "./draggable_controller";
application.register("draggable", DraggableController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import TextareaAutosizeController from "./textarea_autosize_controller";
application.register("textarea-autosize", TextareaAutosizeController);

import ToastController from "./toast_controller";
application.register("toast", ToastController);
